In [6]:
import torch
from torch.nn.utils.rnn import pad_sequence

In [7]:
# 定义数据：3个长度不同的序列
seq1 = torch.randint(1000, (10, ))
seq2 = torch.randint(1000, (5, ))
seq3 = torch.randint(1000, (13, ))
print(seq1)
print(seq2)
print(seq3)

tensor([ 15,  59, 431, 816, 562, 798, 641, 890, 280, 437])
tensor([886, 475, 985, 146, 552])
tensor([535,   2, 814, 990, 373, 447, 736, 178, 468,  46, 304, 607, 174])


In [8]:
# 将3条数据合并成一个batch
seq_list = [seq1, seq2, seq3]
print(seq_list)

[tensor([ 15,  59, 431, 816, 562, 798, 641, 890, 280, 437]), tensor([886, 475, 985, 146, 552]), tensor([535,   2, 814, 990, 373, 447, 736, 178, 468,  46, 304, 607, 174])]


In [9]:
seq_batch = pad_sequence(seq_list, batch_first=True, padding_value=10)    
print(seq_batch)
print(seq_batch.shape)

tensor([[ 15,  59, 431, 816, 562, 798, 641, 890, 280, 437,  10,  10,  10],
        [886, 475, 985, 146, 552,  10,  10,  10,  10,  10,  10,  10,  10],
        [535,   2, 814, 990, 373, 447, 736, 178, 468,  46, 304, 607, 174]])
torch.Size([3, 13])
