In [10]:
import math
import torch

In [11]:
# torch.set_printoptions(sci_mode=False, precision=6)
torch.manual_seed(42)

In [12]:
SEQ_LEN = 4
dk = 64

# 定义 Q、K、V
Q = torch.randn(size=(SEQ_LEN, dk), requires_grad=True)
K = torch.randn(size=(SEQ_LEN, dk), requires_grad=True)
V = torch.randn(SEQ_LEN, dk)

In [13]:
# 按照公式计算注意力评分（点积评分）
scores = Q @ K.T / math.sqrt(dk)
print(scores)

tensor([[-0.2633,  1.2097, -0.2490, -0.7624],
        [-0.3051, -0.2159,  0.6041, -1.6504],
        [ 0.3426,  1.4615, -0.4097, -1.0089],
        [-0.8301,  1.5057, -1.1797,  0.6592]], grad_fn=<DivBackward0>)


In [14]:
# 计算注意力权重
weights = torch.softmax(scores, dim=-1)
print(weights)

tensor([[0.1432, 0.6246, 0.1452, 0.0869],
        [0.2068, 0.2261, 0.5133, 0.0539],
        [0.2087, 0.6389, 0.0984, 0.0540],
        [0.0607, 0.6274, 0.0428, 0.2691]], grad_fn=<SoftmaxBackward0>)


In [15]:
# 模拟一个损失函数，反向传播
weights[0, 0].backward()

In [16]:
# 查看梯度
print(Q.grad)
print(K.grad)

tensor([[-0.0149,  0.0161, -0.0328, -0.0089, -0.0310,  0.0064,  0.0007,  0.0101,
         -0.0287, -0.0029,  0.0319,  0.0077,  0.0125,  0.0031, -0.0197, -0.0045,
         -0.0328,  0.0114, -0.0466,  0.0013, -0.0110, -0.0050,  0.0333,  0.0026,
          0.0107,  0.0151,  0.0089,  0.0011, -0.0083,  0.0230,  0.0078,  0.0028,
          0.0195, -0.0176, -0.0073,  0.0065,  0.0008,  0.0100, -0.0021, -0.0171,
          0.0117, -0.0130,  0.0141,  0.0143,  0.0173,  0.0111,  0.0258, -0.0119,
          0.0081, -0.0152, -0.0110, -0.0376,  0.0021,  0.0131, -0.0328, -0.0332,
          0.0040, -0.0120,  0.0111, -0.0192, -0.0058, -0.0141,  0.0225, -0.0099],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000, 

In [17]:
# 计算上下文向量
context_vector = weights @ V
print(context_vector)
print(context_vector.shape)

tensor([[-8.5474e-01, -6.3932e-01,  4.4517e-01, -3.0440e-01, -8.9369e-01,
         -1.2455e-01, -5.9357e-01,  1.2548e+00, -2.7757e-01, -8.3335e-01,
          2.5466e-01,  1.6571e-01, -4.9267e-01, -1.3515e-01, -1.0669e+00,
         -6.7026e-01,  2.5390e-01, -2.2305e-01,  6.1569e-01, -1.4341e-01,
         -4.3505e-01, -4.6071e-04,  2.9325e-01, -8.4706e-01,  2.1691e-01,
         -6.3715e-01, -6.5829e-03,  2.4631e-01,  4.9757e-01,  1.8242e-01,
          1.1589e+00,  4.2959e-02, -1.0903e+00,  1.2077e+00, -6.6465e-01,
          5.1503e-01, -4.1608e-01, -1.3455e+00,  7.5480e-01,  1.6706e-01,
         -6.0836e-01,  7.9339e-01,  1.1177e+00,  1.2643e-01,  2.4810e-01,
          4.6125e-02,  2.4753e-01,  6.5887e-01,  2.9707e-02,  7.3286e-01,
         -4.8993e-01,  2.0774e-01,  2.8236e-01, -5.9627e-03,  3.4745e-01,
          4.6201e-02, -5.5325e-01, -1.4126e-01,  1.0477e+00,  8.8711e-01,
         -7.2106e-02,  1.1157e+00,  2.7816e-01,  5.7797e-01],
        [-1.1026e+00, -2.0920e-01,  9.8238e-01,  9