In [2]:
import torch.nn as nn

## 模型定义

In [3]:
# 定义 Transformer 模型
model = nn.Transformer(
    d_model=64,
    nhead=8,
    num_encoder_layers=3,
    num_decoder_layers=3,
    dim_feedforward=256,
    batch_first=True,
)

In [4]:
print(model)

Transformer(
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-2): 3 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=64, out_features=64, bias=True)
        )
        (linear1): Linear(in_features=64, out_features=256, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=256, out_features=64, bias=True)
        (norm1): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
    (norm): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
  )
  (decoder): TransformerDecoder(
    (layers): ModuleList(
      (0-2): 3 x TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=64, out_feature

## 前向传播

In [5]:
import torch

In [6]:
# 定义源序列和目标序列
src = torch.randn(32, 10, 64)
tgt = torch.randn(32, 24, 64)

In [7]:
# 前向传播
output = model(src, tgt)
print(output.shape)

torch.Size([32, 24, 64])


## 编码

In [8]:
memory = model.encoder(src)
print(memory.shape)

torch.Size([32, 10, 64])


## 解码

In [9]:
output = model.decoder(tgt, memory)
print(output.shape)

torch.Size([32, 24, 64])


In [10]:
# 验证矩阵加法的广播
x = torch.randint(10, (2, 3, 5))
part_pe = torch.randint(10, (3, 5))
print(x)
print(part_pe)

tensor([[[2, 1, 8, 3, 2],
         [0, 1, 7, 3, 6],
         [0, 9, 8, 4, 8]],

        [[3, 4, 0, 7, 5],
         [1, 7, 9, 2, 0],
         [4, 6, 3, 0, 3]]])
tensor([[6, 8, 9, 5, 9],
        [1, 6, 7, 4, 9],
        [9, 4, 8, 4, 9]])


In [11]:
y = x + part_pe
print(y)
print(y.shape)

tensor([[[ 8,  9, 17,  8, 11],
         [ 1,  7, 14,  7, 15],
         [ 9, 13, 16,  8, 17]],

        [[ 9, 12,  9, 12, 14],
         [ 2, 13, 16,  6,  9],
         [13, 10, 11,  4, 12]]])
torch.Size([2, 3, 5])


In [16]:
# 测试 argmax
input = torch.randn(32, 10, 64)
output = torch.argmax(input, dim=-1, keepdim=True)
print(output.shape)

torch.Size([32, 10, 1])


In [14]:
print(input[:, -1, :].shape)
output = torch.argmax(input[:, -1, :], dim=-1)
print(output.shape)

torch.Size([32, 64])
torch.Size([32])


In [15]:
output = torch.argmax(input[:, -1, :], dim=-1, keepdim=True)
print(output.shape)

torch.Size([32, 1])
